---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neo-fixit.fullname" . }}
  labels:
    {{- include "neo-fixit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "neo-fixit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # name: fixit
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "neo-fixit.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "v2" }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        # livenessProbe:
        #   httpGet:
        #     path: /demo/
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /demo/
        #     port: http